server:
  port: 8091
  address: 0.0.0.0

allowed:
  origins: http://localhost:8091
  description: Prod server

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prod_loanms
    username: postgres
    password: shaxzod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: LOAN-MANAGEMENT-SYSTEM-PROD
    XApiKey: prod123
  mail:
    host: smtp.gmail.com
    port: 587
    username: hospital.management.system0@gmail.com
    password: sknmyykdsjyqyscz
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true
jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848567890iuyiu67567886578uyutuio7865467897654678965467uior678545
  access:
    expiry: 86400000
  refresh:
    expiry: 604800000